dist: trusty
language: php

php:
- 5.5
- 5.6
- 7.0

#before_install:
#- if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.5" ]]; then composer require --dev --no-update phpunit/phpunit ~4; fi

install:
- composer install --no-interaction --no-suggest

before_script:
- phpenv config-rm xdebug.ini

script:
- ./vendor/bin/phing all
